dist: xenial
language: python
python:
  - '3.7.2'

sudo : required
services:
  - docker

before_install:
  - docker build -t farhansajid2/django-test -f ./docker/dev/Dockerfile.dev ./docker/dev

script:
  - docker run farhansajid2/django-test python manage.py test

after_success:
  - docker build -t farhansajid2/django-app ./docker/prod/
  - docker build -t farhansajid2/django-nginx ./nginx/

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker hub
  - docker push farhansajid2/django-app
  - docker push farhansajid2/django-nginx