dist: xenial
language: python
python:
  - '3.7'

sudo : required
services:
  - docker

before_install:
  - docker build -t farhansajid2/django-test -f ./docker/dev/Dockerfile.dev .

script:
  - docker run farhansajid2/django-test python manage.py test

after_success:
  - docker build -t farhansajid2/django-app -f ./docker/prod/Dockerfile .
  - docker build -t farhansajid2/django-nginx -f ./nginx/Dockerfile .

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker hub
  - docker push farhansajid2/django-app
  - docker push farhansajid2/django-nginx


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "deployment"
  env: "Deployment-env"
  bucket_name: "elasticbeanstalk-us-east-2-250900492900"
  bucket_path: "django-blog-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"