version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev

    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - GOOGLE_USER=${GOOGLE_USER}
      - DJANGO_SETTINGS_MODULE=django_project.settings.test # the mysql settings

    volumes:
      - ./:/app

    ports:
      - '8990:8990'

    depends_on:
      - postgres

  test:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev

    command: ["python", "manage.py", "test"]
    volumes:
      - ./:/app

  postgres:
    image: 'postgres'

  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "9000:80"