version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile

    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - GOOGLE_USER=${GOOGLE_USER}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - DJANGO_SETTINGS_MODULE=django_project.settings.production # production environment

    command: gunicorn -w 4 django_project.wsgi -b 0.0.0.0:8990
    volumes:
      - static_volume:/var/www/blog/static

    depends_on:
      - postgres

  postgres:
    image: 'postgres'

  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8990:80"
    volumes:
      - static_volume:/var/www/blog/static

    depends_on:
      - app

volumes:
  static_volume:
